### ISSUE TITLE
Balancing Ideas for the character

### ISSUE THREAD

**Issue by Possiblehomicide** [Dragonyck/Shyvana#1]
Hello,

I recently picked up your rendition of Shyvana and gave it a shot. It felt amazing! I didn't realize that I wanted to be a dragon in ROR2 with massive AOE and hard hits. I had so much fun with it... until about stage 3.

Don't get me wrong, I love the thought and appreciation you put into the character, I love their amazing mobility in dragon form, their stellar damage, and I think the time spent in human form vs. dragon form is well balanced, however the dragon form is just too squishy.

In human form, the utility skill does a great job in keeping the melee character alive in brawls with countless enemies. I find that its almost always a bad idea to swap to the dragon form. While I get a massive boost to my damage and mobility, the gargantuan hitbox makes it impossible to dodge any projectiles, and while the character is healed to full on transformation, the lack of any combat sustain ends up with me 100-0 in only a second or two.

Again, I love this mod and I appreciate all of the though that went into it.

Maybe give a shit ton of armor to the dragon form? Making it just overall tankier? This would alleviate my issues with this form in the early game, but would still leave her vulnerable in the late.

Second idea is to lessen the healing power of base form shyvana and instead give it to the dragon form. Maybe guaranteed lifesteal on the auto attack? Or you could have the aura permanently around the dragon (although tune down the numbers if it's on 24/7).

Finally, while I'm not sure how balanced this would be, give shyvana the equivalent of like 10+ Repulsion Armor Plates when she transforms, to lower the danger of swarms while keeping bosses more or less the same (blind pests were the worst when transformed). The ideal way to do it would be to start at like 5 plates, and scale 1-2 each player level. This would keep the damage from swarms low but still let her be outscaled if she falls behind.

Overall, amazing mod/port, I've had a lot of fun with it so far, and I look forward to it being updated in the future!

Thanks,

-Phomicide

**Comment by Dragonyck** [comment]
The commissioner (Nines) complied, armor per level was added and Ruin now heals per tick. 
I don't keep track of git issues, so next time you can just dm or ping me on ror2modcord @dragonyck
